---
- name: Debug namespace variable
  ansible.builtin.debug:
    msg: "Namespace value: {{ namespace }}"

- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default

- name: Apply MongoDB Secret
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/mongo/mongo-secret.yaml"
    namespace: default

- name: Apply MongoDB Persistent Volume Claim
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/mongo/mongo-pvc.yaml"
    namespace: default

- name: Apply MongoDB ConfigMap
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/config-maps/config_map-mongodb.yaml"
    namespace: default

- name: Apply MongoDB Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/mongo/mongo-deployment.yaml"
    namespace: default

- name: Apply MongoDB Service
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/mongo/mongo-service.yaml"
    namespace: default

- name: Apply FastAPI Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/app/fastapi-deployment.yaml"
    namespace: default

- name: Apply FastAPI Service
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/app/fastapi-service.yaml"
    namespace: default

- name: Apply Frontend Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/frontend/frontend-deployment.yaml"
    namespace: default

- name: Apply Frontend Service
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/frontend/frontend-service.yaml"
    namespace: default