---
- name: Testing Playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Create directory
      file:
      path: /mnt/c/Users/1/Desktop/fastapi crud/manager-password/ansible/test
      state: directory
      mode: '0755'
    - name: Create file
      copy:
        content: "Hello from Ansible!"
        dest: /mnt/c/Users/1/Desktop/fastapi crud/manager-password/ansible/test/hello.txt