apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
spec:
 hostIPC: false
 hostPID: false
 hostNetwork: false
 hostPorts:
  - min: 3000
    max: 32767
  - min: 3000
    max: 32767
privileged: false
readOnlyRootFilesystem: false
runAsUser:
  rule: RunAsAny
fsGroup:
  rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  selinux:
    rule: RunAsAny
  volumes:
    - '*'