version: "3.8"

services:
  web:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./manager-password/:/usr/src/app/
    ports:
      - "8002:8000"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - loki
    
    
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    environment:
      - LOKI_ENDPOINT

  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports: 
      - "27018:27017"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/prometheus_data  
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/grafana_data 



networks:
  fastapi_network:
    driver: bridge