version: "3.8"

services:
  fastapi-app:
    build:
      context: ./manager-password  
      dockerfile: Dockerfile       
    env_file:
      - ./manager-password/.env
    ports:
      - "8000:8000"
    networks:
      - web
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend          
      dockerfile: Dockerfile       
    ports:
      - "80:80"                    
    networks:
      - web
    restart: unless-stopped
    depends_on:
      - fastapi-app                

networks:
  web:
    driver: bridge                 