name: ansible


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  ansible:
    name: 'Ansible Configuration'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    
    steps:
      - name: Run ansible-playbook
        run: ansible-playbook deploy_kuber.yml

      - name: Write inventory to file
        env:
          INVENTORY: ${{ secrets.INVENTORY }}
      
      - name: Syntax checkout
        run: ansible-playbook --syntax-check deploy_kuber -i inventory