name: Deploy Monitoring Stack
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build monitoring stack (Prometheus & Grafana)
        run: docker compose -f /cyber-tulas/manager-password/monitoring/docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Check Prometheus health
        run: |
          curl -sSf http://localhost:9090/-/healthy || exit 1

      - name: Check Grafana is running
        run: |
          curl -sSf http://localhost:3000 || exit 1

