name: "GCP Terraform Deploy & Security Scan"

on:
  push:
    branches:
      - main  

jobs:
  security-scan:
    name: "Security Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Run Semgrep
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep --config=auto

      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  terraform-deploy:
    name: "Terraform Apply"
    needs: security-scan 
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="project_id=cyber-tulas"