name: kubescape-scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  kubescape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash
          echo "$HOME/.kubescape" >> $GITHUB_PATH
          kubescape version

      - name: Create output folder
        run: mkdir -p results

      - name: Run kubescape scan
        run: |
          kubescape scan framework nsa --format json --output results/kubescape-results.json

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-results
          path: results/kubescape-results.json
