name: kubescape-scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
          echo "$HOME/.kubescape" >> $GITHUB_PATH

      - name: Verify installation
        run: ~/.kubescape/kubescape version

      - name: Create results directory
        run: mkdir -p results

      - name: Run kubescape scan
        run: ~/.kubescape/kubescape scan framework nsa --format json --output results/kubescape-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-results
          path: results/kubescape-results.json
